const students = [
  { value: 'Anilove Marie Acopiado', label: 'Acopiado', section: 'Block C' },
  { value: 'Giancarlo Albeos', label: 'Albeos', section: 'Block C' },
  { value: 'Vince Raphael Alemania', label: 'Alemania', section: 'Block A' },
  { value: 'Raffy Mae Alidon', label: 'Alidon', section: 'Block A' },
  { value: 'Darena May Allosada', label: 'Allosada', section: 'Block A' },
  { value: 'Crystille Jean Amaquiton', label: 'Amaquiton', section: 'Block B' },
  { value: 'Francisco Amit', label: 'Amit', section: 'Block B' },
  { value: 'Jaycee Mariel Amoyo', label: 'Amoyo', section: 'Block B' },
  { value: 'Sophia Lorraine Aradanas', label: 'Aradanas', section: 'Block A' },
  { value: 'Khirk Johann Ayag', label: 'Ayag', section: 'Block A' },
  { value: 'Christian Kyle Baclay', label: 'Baclay', section: 'Block A' },
  { value: 'Jhelbeth Erika Balabat', label: 'Balabat', section: 'Block A' },
  { value: 'Aila Rose Balili', label: 'Balili', section: 'Block A' },
  { value: 'Berenice Benitez', label: 'Benitez', section: 'Block A' },
  { value: 'Jesse Biliran', label: 'Biliran', section: 'Block B' },
  { value: 'Neil Christian Bolotaolo', label: 'Bolotaolo', section: 'Block A' },
  { value: 'Johnaxxel Mark Bonjoc', label: 'Bonjoc', section: 'Block A' },
  { value: 'John Rex Borbon', label: 'Borbon', section: 'Block B' },
  { value: 'Jaye Ford Camasura', label: 'Camasura', section: 'Block A' },
  { value: 'Fria Mae Camello', label: 'Camello', section: 'Block B' },
  { value: 'Vock Laurence Canlas', label: 'Canlas', section: 'Block A' },
  { value: 'Sheen Santos Capadngan', label: 'Capadngan', section: 'Block A' },
  {
    value: 'Heart Methody Castañares',
    label: 'Castañares',
    section: 'Block A',
  },
  { value: 'Micah Emmanuelle Ceniza', label: 'Ceniza', section: 'Block A' },
  { value: 'Jamaica Anel Conde', label: 'Conde', section: 'Block A' },
  { value: 'Rophi Denish Condor', label: 'Condor', section: 'Block B' },
  { value: 'Fatima Jonam Dangcogan', label: 'Dangcogan', section: 'Block C' },
  { value: 'Louise Fermin Deiparine', label: 'Deiparine', section: 'Block A' },
  {
    value: 'Emmanuelli Raphael Dela torre',
    label: 'Dela torre',
    section: 'Block A',
  },
  { value: 'Caroline Doloricon', label: 'Doloricon', section: 'Block A' },
  { value: 'Mary Deanne Domail', label: 'Domail', section: 'Block A' },
  { value: 'Neil Jasper Draper', label: 'Draper', section: 'Block B' },
  { value: 'Joseph Duron', label: 'Duron', section: 'Block A' },
  { value: 'Ira Belle Electona', label: 'Electona', section: 'Block B' },
  { value: 'Nathan Josiah Elmido', label: 'Elmido', section: 'Block B' },
  { value: 'Lyana Rae Espina', label: 'Espina', section: 'Block B' },
  { value: 'Jhon Dustin Gabutan', label: 'Gabutan', section: 'Block A' },
  { value: 'Reigne Hanneiken Gaite', label: 'Gaite', section: 'Block C' },
  { value: 'Roddneil Gemina', label: 'Gemina', section: 'Block A' },
  { value: 'Gerard Niño Gorrero', label: 'Gorrero', section: 'Block B' },
  { value: 'Gerxam Intano', label: 'Intano', section: 'Block B' },
  { value: 'Florence Jeramie Legaspi', label: 'Legaspi', section: 'Block B' },
  { value: 'Jomar Jr. Lepiten', label: 'Lepiten', section: 'Block C' },
  { value: 'Isabela Lobitaña', label: 'Lobitaña', section: 'Block A' },
  { value: 'Reynald Tim Lopos', label: 'Lopos', section: 'Block B' },
  { value: 'Judiel Macachor', label: 'Macachor', section: 'Block B' },
  { value: 'Ruzgel Madera', label: 'Madera', section: 'Block A' },
  {
    value: 'Ezra Madafaking Magbanua',
    label: 'Magbanua',
    section: 'Block B',
    nickname: 'Madafaking bitch',
  },
  { value: 'Luis Antonio Magpayo', label: 'Magpayo', section: 'Block C' },
  { value: 'Lindsay Marie Manlegro', label: 'Manlegro', section: 'Block C' },
  { value: 'Christian Manso', label: 'Manso', section: 'Block B' },
  { value: 'Jarell Brigette Manuel', label: 'Manuel', section: 'Block A' },
  { value: 'Basil Xavier Mendoza', label: 'Mendoza', section: 'Block C' },
  { value: 'Micaela Milana', label: 'Milana', section: 'Block B' },
  { value: 'Maxell Milay', label: 'Milay', section: 'Block C' },
  {
    value: 'Charles Artsmon Mondragon',
    label: 'Mondragon',
    section: 'Block C',
  },
  { value: 'Charles Rene Monsales', label: 'Monsales', section: 'Block B' },
  { value: 'Bryan Rod Montecillo', label: 'Montecillo', section: 'Block B' },
  { value: 'Shannen Marri Morikawa', label: 'Morikawa', section: 'Block B' },
  {
    value: 'Neshil Ezzabelle Namocatcat',
    label: 'Namocatcat',
    section: 'Block B',
  },
  { value: 'Christian Nicolas', label: 'Nicolas', section: 'Block C' },
  { value: 'Jam Angel Ong', label: 'Ong', section: 'Block B' },
  { value: 'Akhyra Oplado', label: 'Oplado', section: 'Block C' },
  { value: 'Leigh Therese Palahang', label: 'Palahang', section: 'Block A' },
  { value: 'Josh Nathaniel Palaña', label: 'Palaña', section: 'Block C' },
  { value: 'Raya Alessandra Partosa', label: 'Partosa', section: 'Block C' },
  { value: 'Justine Pepito', label: 'Pepito', section: 'Block C' },
  { value: 'Jeryn Claudette Portrias', label: 'Portrias', section: 'Block C' },
  { value: 'Justin Gabriel Rallon', label: 'Rallon', section: 'Block B' },
  { value: 'Hellerie Hope Rendon', label: 'Rendon', section: 'Block C' },
  { value: 'Danah Gould Ricamor', label: 'Ricamor', section: 'Block C' },
  { value: 'Desiderio Jr. Rivera', label: 'Rivera', section: 'Block C' },
  { value: 'Samantha Grace Sagrado', label: 'Sagrado', section: 'Block C' },
  { value: 'Adrian Sajulga', label: 'Sajulga', section: 'Block B' },
  { value: 'Stephen Clint Sales', label: 'Sales', section: 'Block C' },
  { value: 'Clark Louise Sevilla', label: 'Sevilla', section: 'Block C' },
  { value: 'Andrei Zoe Solante', label: 'Solante', section: 'Block C' },
  { value: 'John Lloyd Sundo', label: 'Sundo', section: 'Block A' },
  { value: 'Milchival Runes Vincent Taer', label: 'Taer', section: 'Block C' },
  { value: 'Atasha Mykaelai Talon', label: 'Talon', section: 'Block B' },
  { value: 'Meg Torralba', label: 'Torralba', section: 'Block B' },
  { value: 'Andry Joseph Tumacole', label: 'Tumacole', section: 'Block A' },
  { value: 'Jan Eul Anthony Ucang', label: 'Ucang', section: 'Block C' },
  { value: 'Ethan Jithro Umali', label: 'Umali', section: 'Block C' },
  { value: 'Sophia Therese Unson', label: 'Unson', section: 'Block C' },
  { value: 'Vaughn Matthew Valle', label: 'Valle Vaughn', section: 'Block B' },
  { value: 'Vince Louie Valle', label: 'Valle Vince', section: 'Block B' },
  { value: 'Gaile Lynell Yuag', label: 'Yuag', section: 'Block C' },
  { value: 'Pheobe Nerice Yusingbo', label: 'Yusingbo', section: 'Block C' },
  { value: 'James River Philip Yuson', label: 'Yuson', section: 'Block C' },
];
export default students;
