const students = [
  {
    value: 'Adrian Sajulga',
    label: 'Sajulga',
    section: 'Block B',
    nickname: 'Drian / Yan / docx (pdf) file',
  },
  {
    value: 'Aila Rose Balili',
    label: 'Balili',
    section: 'Block A',
    nickname: 'Follow @aiseketch on ig for good luck',
  },
  {
    value: 'Akhyra Oplado',
    label: 'Oplado',
    section: 'Block C',
    nickname: 'Li, https://ko-fi.com/chiakiakira',
  },
  {
    value: 'Andrei Zoe Solante',
    label: 'Solante',
    section: 'Block C',
    nickname: 'Drei / Hamon',
  },
  {
    value: 'Andry Joseph Tumacole',
    label: 'Tumacole',
    section: 'Block A',
    nickname: 'top 1 sa batch',
  },
  {
    value: 'Anilove Marie Acopiado',
    label: 'Acopiado',
    section: 'Block C',
    nickname: 'Nilab',
  },
  {
    value: 'Atasha Mykaelai Talon',
    label: 'Talon',
    section: 'Block B',
    nickname: 'tash | taling',
  },
  {
    value: 'Basil Xavier Mendoza',
    label: 'Mendoza',
    section: 'Block C',
    nickname: '....',
  },
  {
    value: 'Berenice Benitez',
    label: 'Benitez',
    section: 'Block A',
    nickname: 'Berns',
  },
  {
    value: 'Bryan Rod Montecillo',
    label: 'Montecillo',
    section: 'Block B',
    nickname: 'bry ૮ ˙Ⱉ˙ ა',
  },
  {
    value: 'Caroline Doloricon',
    label: 'Doloricon',
    section: 'Block A',
    nickname: 'THE miz karolayn',
  },
  {
    value: 'Charles Artsmon Mondragon',
    label: 'Mondragon',
    section: 'Block C',
    nickname: 'monMon the dragon',
  },
  {
    value: 'Charles Rene Monsales',
    label: 'Monsales',
    section: 'Block B',
    nickname: 'Charles/ Rene/ Monsales / chuuni',
  },
  {
    value: 'Christian Kyle Baclay',
    label: 'Baclay',
    section: 'Block A',
    nickname: '....',
  },
  {
    value: 'Christian Manso',
    label: 'Manso',
    section: 'Block B',
    nickname: 'ian',
  },
  {
    value: 'Christian Nicolas',
    label: 'Nicolas',
    section: 'Block A',
    nickname: 'oy si nics gi hyperventilate',
  },
  {
    value: 'Clark Louise Sevilla',
    label: 'Sevilla',
    section: 'Block C',
    nickname: 'sevs, louise, sevi, kapitan smooth1e',
  },
  {
    value: 'Crystille Jean Amaquiton',
    label: 'Amaquiton',
    section: 'Block B',
    nickname: 'crystille, eomma, eommalda',
  },
  {
    value: 'Danah Gould Ricamor',
    label: 'Ricamor',
    section: 'Block C',
    nickname: 'danahbabes',
  },
  {
    value: 'Darena May Allosada',
    label: 'Allosada',
    section: 'Block A',
    nickname: '....',
  },
  {
    value: 'Desiderio Jr. Rivera',
    label: 'Rivera',
    section: 'Block C',
    nickname: 'DJ/Deejay, Dij',
  },
  {
    value: 'Emmanuelli Rafael Dela Torre',
    label: 'Dela Torre',
    section: 'Block A',
    nickname: 'Elli',
  },
  {
    value: 'Ethan Jithro Umali',
    label: 'Umali',
    section: 'Block C',
    nickname: 'Eytawn / Tan',
  },
  {
    value: 'Ezra Madafaking Magbanua',
    label: 'Magbanua',
    section: 'Block B',
    nickname: 'the madafaking bitch',
  },
  {
    value: 'Fatima Jonam Dangcogan',
    label: 'Dangcogan',
    section: 'Block C',
    nickname: 'jdngcgn',
  },
  {
    value: 'Florence Jeramie Legaspi',
    label: 'Legaspi',
    section: 'Block B',
    nickname: '....',
  },
  {
    value: 'Francisco Amit daTURD',
    label: 'Amit',
    section: 'Block B',
    nickname: 'Amite Kudasai',
  },
  {
    value: 'Fria Mae Camello',
    label: 'Camello',
    section: 'Block B',
    nickname: 'priyamii',
  },
  {
    value: 'Gaile Lynell Yuag',
    label: 'Yuag',
    section: 'Block C',
    nickname: 'baby girl',
  },
  {
    value: 'Gerard Niño Gorrero',
    label: 'Gorrero',
    section: 'Block B',
    nickname: 'Gors/Pader Gors/Papa Bear/Dei',
  },
  {
    value: 'Gerxam Intano',
    label: 'Intano',
    section: 'Block B',
    nickname: 'Xam',
  },
  {
    value: 'Giancarlo Albeos',
    label: 'Albeos',
    section: 'Block C',
    nickname: 'Gian, yan-yan',
  },
  {
    value: 'Heart Methody Castañares',
    label: 'Castañares',
    section: 'Block A',
    nickname: 'heart / heart meth',
  },
  {
    value: 'Hellerie Hope Rendon',
    label: 'Rendon',
    section: 'Block C',
    nickname: 'hopia / pya',
  },
  {
    value: 'Ira Belle Electona',
    label: 'Electona',
    section: 'Block B',
    nickname: 'ayrabil',
  },
  {
    value: 'Isabela Lobitaña',
    label: 'Lobitaña',
    section: 'Block A',
    nickname: '....',
  },
  {
    value: 'Jam Angel Ong',
    label: 'Ong',
    section: 'Block B',
    nickname: 'miss ong',
  },
  {
    value: 'Jamaica Anel Conde',
    label: 'Conde',
    section: 'Block A',
    nickname: 'jamayot || my little munchkin',
  },
  {
    value: 'James River Philip Yuson',
    label: 'Yuson',
    section: 'Block C',
    nickname: 'Shun / Jiver / Phil',
  },
  {
    value: 'Jan Eul Anthony Ucang',
    label: 'Ucang',
    section: 'Block C',
    nickname: 'J.E.A.N.U.',
  },
  {
    value: 'Jarell Brigette Manuel',
    label: 'Manuel',
    section: 'Block C',
    nickname: 'chibi || void chicken from stardew valley',
  },
  {
    value: 'Jaycee Mariel Amoyo',
    label: 'Amoyo',
    section: 'Block B',
    nickname: 'that one swimmer Jaycee',
  },
  {
    value: 'Jaye Ford Camasura',
    label: 'Camasura',
    section: 'Block A',
    nickname: 'pord',
  },
  {
    value: 'Jeryn Claudette Portrias',
    label: 'Portrias',
    section: 'Block C',
    nickname: 'jerlyn, jerlalen',
  },
  {
    value: 'Jesse Biliran',
    label: 'Biliran',
    section: 'Block B',
    nickname: 'Jess',
  },
  {
    value: 'Jhelbeth Erika Balabat',
    label: 'Balabat',
    section: 'Block A',
    nickname: 'jhel, jilbit, jebel',
  },
  {
    value: 'Jhon Dustin Gabutan',
    label: 'Gabutan',
    section: 'Block A',
    nickname: 'Dustin, daskween',
  },
  {
    value: 'John Lloyd Sundo',
    label: 'Sundo',
    section: 'Block A',
    nickname: 'IHaveFreeCandy',
  },
  {
    value: 'John Rex Borbon',
    label: 'Borbon',
    section: 'Block B',
    nickname: 'Mai-san / 70294325 1v1 ml / mafia boss / jay ar',
  },
  {
    value: 'Johnaxxel Mark Bonjoc',
    label: 'Bonjoc',
    section: 'Block A',
    nickname: 'Axxel',
  },
  {
    value: 'Jomar Jr. Lepiten',
    label: 'Lepiten',
    section: 'Block C',
    nickname: 'Jo/ Mar/ Jomar/ babe/ jhepoy Dizon',
  },
  {
    value: 'Joseph Duron',
    label: 'Duron',
    section: 'Block A',
    nickname: '3kmitothebestburger',
  },
  {
    value: 'Josh Nathaniel Palaña',
    label: 'Palaña',
    section: 'Block C',
    nickname: 'josh',
  },
  {
    value: 'Judiel Macachor',
    label: 'Macachor',
    section: 'Block B',
    nickname: 'jo',
  },
  {
    value: 'Justin Gabriel Rallon',
    label: 'Rallon',
    section: 'Block B',
    nickname: 'Justin, Cybr',
  },
  {
    value: 'Justine Pepito',
    label: 'Pepito',
    section: 'Block C',
    nickname: 'Pits, Pepito, Pepits',
  },
  {
    value: 'Khirk Johann Ayag',
    label: 'Ayag',
    section: 'Block A',
    nickname: 'bukog',
  },
  {
    value: 'Leigh Therese Palahang',
    label: 'Palahang',
    section: 'Block A',
    nickname: 'eight',
  },
  {
    value: 'Lindsay Marie Manlegro',
    label: 'Manlegro',
    section: 'Block C',
    nickname: 'Lia Marie',
  },
  {
    value: 'Louise Fermin Deiparine',
    label: 'Deiparine',
    section: 'Block A',
    nickname: 'Louise/Lowes/Mr.Fahrenheit/TravellinAtTheSpeedOfLight',
  },
  {
    value: 'Luis Antonio Magpayo',
    label: 'Magpayo',
    section: 'Block C',
    nickname: 'Luis',
  },
  {
    value: 'Lyana Rae Espina',
    label: 'Espina',
    section: 'Block B',
    nickname: '....',
  },
  {
    value: 'Mary Deanne Domail',
    label: 'Domail',
    section: 'Block A',
    nickname: 'Ayen, Yien,  Miridin, Maria Diana, dominant_ayen',
  },
  {
    value: 'Maxell Milay',
    label: 'Milay',
    section: 'Block C',
    nickname: 'mirai',
  },
  {
    value: 'Meg Torralba',
    label: 'Torralba',
    section: 'Block B',
    nickname:
      'megu | meggie | ur fav idiot | m e r m e g onspotifylezgo | M3G | trampoline',
  },
  {
    value: 'Micaela Milana',
    label: 'Milana',
    section: 'Block B',
    nickname: 'mizmicae',
  },
  {
    value: 'Micah Emmanuelle Ceniza',
    label: 'Ceniza',
    section: 'Block A',
    nickname: 'micah mae',
  },
  {
    value: 'Milchival Runes Vincent Taer',
    label: 'Taer',
    section: 'Block C',
    nickname: 'milch, mitch, Haachama',
  },
  {
    value: 'Nathan Josiah Elmido',
    label: 'Elmido',
    section: 'Block B',
    nickname: 'Sir Nate // nuggetman',
  },
  {
    value: 'Neil Christian Bolotaolo',
    label: 'Bolotaolo',
    section: 'Block A',
    nickname:
      'Yagoo / Zach Madiq / Pedro Pile / Dragonslayer / Hara Seer / Young (Child) Freddie Thor / Chikadodly',
  },
  {
    value: 'Neil Jasper Draper',
    label: 'Draper',
    section: 'Block B',
    nickname: 'nil | draps',
  },
  {
    value: 'Neshil Ezzabelle Namocatcat',
    label: 'Namocatcat',
    section: 'Block B',
    nickname: 'Eshi',
  },
  {
    value: 'Pheobe Nerice Yusingbo',
    label: 'Yusingbo',
    section: 'Block C',
    nickname: 'pb / pbyangg / yang',
  },
  {
    value: 'Raffy Mae Alidon',
    label: 'Alidon',
    section: 'Block A',
    nickname: 'Raffy / Raf / Mae / Pyang / Taffee / RaffyMaeh',
  },
  {
    value: 'Raya Alessandra Partosa',
    label: 'Partosa',
    section: 'Block C',
    nickname: 'wyaii | rayatata',
  },
  {
    value: 'Reigne Hanneiken Gaite',
    label: 'Gaite',
    section: 'Block C',
    nickname: 'Reigne',
  },
  {
    value: 'Reynald Tim Lopos',
    label: 'Lopos',
    section: 'Block B',
    nickname: 'lops / timyong / timmeh / timothy / man1c / Sue Bumo T. Tiko',
  },
  {
    value: 'Roddneil Gemina',
    label: 'Gemina',
    section: 'Block A',
    nickname: 'rudnil',
  },
  {
    value: 'Rophi Denish Condor',
    label: 'Condor',
    section: 'Block B',
    nickname: 'Pai',
  },
  {
    value: 'Ruzgel Madera',
    label: 'Madera',
    section: 'Block A',
    nickname: 'kuan rasjel/rg',
  },
  {
    value: 'Samantha Grace Sagrado',
    label: 'Sagrado',
    section: 'Block C',
    nickname: 'stem cause i dont have R / borderline graduatee',
  },
  {
    value: 'Shannen Marri Morikawa',
    label: 'Morikawa',
    section: 'Block B',
    nickname: 'nen',
  },
  {
    value: 'Sheen Santos Capadngan',
    label: 'Capadngan',
    section: 'Block A',
    nickname: 'sheenthesheep',
  },
  {
    value: 'Sophia Lorraine Aradanas',
    label: 'Aradanas',
    section: 'Block A',
    nickname: 'lorraine ♡',
  },
  {
    value: 'Sophia Therese Unson',
    label: 'Unson',
    section: 'Block C',
    nickname: 'soph / pia || gacha addiction era (real) ',
  },
  {
    value: 'Stephen Clint Sales',
    label: 'Sales',
    section: 'Block C',
    nickname: 'tepen / @supersstepan / Kayatarina / eneri <33',
  },
  {
    value: 'Vaughn Matthew Valle',
    label: 'Valle Vaughn',
    section: 'Block B',
    nickname: 'bon',
  },
  {
    value: 'Vince Louie Valle',
    label: 'Valle Vince',
    section: 'Block B',
    nickname: 'pabl0',
  },
  {
    value: 'Vince Raphael Alemania',
    label: 'Alemania',
    section: 'Block A',
    nickname:
      'Lofipop https://youtube.com/channel/UCOA1LVlk5TIv19COMcvMeKg / BawuKog8log',
  },
  {
    value: 'Vock Laurence Canlas',
    label: 'Canlas',
    section: 'Block A',
    nickname: 'Vock / Laurence',
  },
];
export default students;
